server:
    servlet:
        context-path: '/'
    port: 8989

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/myweb?characterEncoding=UTF-8
        username: root
        password: 123

mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.hkd.entity
logging:
    level:
        com.hkd.dao: debug
